/**
 * Minimal ICO parser: picks the largest frame and returns it either as raw PNG bytes (most icons
 * generated by modern tooling embed a PNG frame for larger sizes) or as decoded RGBA pixels for
 * the classic uncompressed 24/32-bit DIB frame format. Palette/compressed DIB frames (rare in
 * practice for real-world favicons) are not supported and return null — callers treat that as a
 * decode failure with a localized message, not a crash.
 */
export interface DecodedIcoFrame {
  kind: 'png'
  bytes: Uint8Array
}

export interface DecodedIcoBitmap {
  kind: 'bitmap'
  width: number
  height: number
  rgba: Uint8ClampedArray
}

export type DecodedIco = DecodedIcoFrame | DecodedIcoBitmap

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]

function isPngSignature(bytes: Uint8Array, offset: number): boolean {
  return PNG_SIGNATURE.every((value, index) => bytes[offset + index] === value)
}

export function decodeIco(buffer: ArrayBuffer): DecodedIco | null {
  const bytes = new Uint8Array(buffer)
  const view = new DataView(buffer)
  if (bytes.length < 6) return null

  const type = view.getUint16(2, true)
  const count = view.getUint16(4, true)
  if (type !== 1 || count === 0) return null

  let bestIndex = -1
  let bestArea = -1
  for (let i = 0; i < count; i += 1) {
    const entryOffset = 6 + i * 16
    if (entryOffset + 16 > bytes.length) break
    const width = bytes[entryOffset] || 256
    const height = bytes[entryOffset + 1] || 256
    const area = width * height
    if (area > bestArea) {
      bestArea = area
      bestIndex = i
    }
  }
  if (bestIndex === -1) return null

  const entryOffset = 6 + bestIndex * 16
  const dataSize = view.getUint32(entryOffset + 8, true)
  const dataOffset = view.getUint32(entryOffset + 12, true)
  if (dataOffset + dataSize > bytes.length || dataSize < 4) return null

  const data = bytes.slice(dataOffset, dataOffset + dataSize)
  if (isPngSignature(data, 0)) return { kind: 'png', bytes: data }

  return decodeDibFrame(data)
}

function decodeDibFrame(data: Uint8Array): DecodedIcoBitmap | null {
  if (data.length < 40) return null
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength)

  const headerSize = view.getUint32(0, true)
  if (headerSize < 40) return null

  const width = view.getInt32(4, true)
  const dibHeight = view.getInt32(8, true)
  const bitCount = view.getUint16(14, true)
  const compression = view.getUint32(16, true)
  if (compression !== 0) return null // BI_RGB only
  if (bitCount !== 24 && bitCount !== 32) return null // palette/compressed frames unsupported

  // ICO DIBs store double the real height (XOR color bitmap + AND mask bitmap stacked).
  const height = Math.abs(dibHeight) / 2
  if (!Number.isInteger(height) || width <= 0 || height <= 0) return null

  const pixelStart = headerSize
  const bytesPerPixel = bitCount / 8
  const rowStride = Math.ceil((width * bytesPerPixel) / 4) * 4
  const colorDataSize = rowStride * height
  if (pixelStart + colorDataSize > data.length) return null

  const rgba = new Uint8ClampedArray(width * height * 4)

  for (let row = 0; row < height; row += 1) {
    // DIB rows are bottom-up.
    const srcRowOffset = pixelStart + (height - 1 - row) * rowStride
    for (let col = 0; col < width; col += 1) {
      const srcOffset = srcRowOffset + col * bytesPerPixel
      const destOffset = (row * width + col) * 4
      const b = data[srcOffset]
      const g = data[srcOffset + 1]
      const r = data[srcOffset + 2]
      const a = bitCount === 32 ? data[srcOffset + 3] : 255
      rgba[destOffset] = r
      rgba[destOffset + 1] = g
      rgba[destOffset + 2] = b
      rgba[destOffset + 3] = a
    }
  }

  if (bitCount === 24) {
    applyAndMask(data, pixelStart + colorDataSize, width, height, rgba)
  }

  return { kind: 'bitmap', width, height, rgba }
}

/** 24-bit DIB frames carry a trailing 1-bit-per-pixel AND mask (1 = transparent) for simple on/off transparency. */
function applyAndMask(data: Uint8Array, maskStart: number, width: number, height: number, rgba: Uint8ClampedArray): void {
  const maskRowStride = Math.ceil(width / 8 / 4) * 4
  if (maskStart + maskRowStride * height > data.length) return

  for (let row = 0; row < height; row += 1) {
    const srcRowOffset = maskStart + (height - 1 - row) * maskRowStride
    for (let col = 0; col < width; col += 1) {
      const byte = data[srcRowOffset + Math.floor(col / 8)]
      const bit = (byte >> (7 - (col % 8))) & 1
      if (bit === 1) {
        const destOffset = (row * width + col) * 4
        rgba[destOffset + 3] = 0
      }
    }
  }
}
